### ISSUE TITLE
Request: Make OnFontChange redraw of screen in new codepage optional

### ISSUE THREAD

**Issue by opicron** [rickparrish/fTelnet#14]
First of all, thank you for such an great telnet client!

I have an board running which makes use of various codepages, even various codepages per screen. When using NetRunner to visit the board I can see both the Amiga and IBM font on the same screen.

I am checking your sourcecode and I see that in crt.ts line 685 there is an OnFontChanged event which triggers the redraw in the new font.

Could we add an switch to prevent redrawing the whole screen in the new codepage?

The board in question is bbs.opicron.eu:23 and the sections are download, queue and newmail if you want to see how I use the codepages :).

Examples:
![Capture2](https://user-images.githubusercontent.com/472432/100122531-c53d9500-2e79-11eb-9f3a-087e9beb00ad.PNG)
![Capture1](https://user-images.githubusercontent.com/472432/100122536-c7075880-2e79-11eb-839b-5900539ef012.PNG)

**Comment by rickparrish** [comment]
I've just pushed a new version with a **SkipRedrawWhenSameFontSize** option, so if you set that to **true** then it'll skip redrawing the entire screen if the new font is the same size as the old font.

Note that a few events force a redraw, for example classic scrollback, selecting text, and possibly others I'm forgetting, so it's not a perfect solution.  Hopefully those aren't features users use often though, in which case it should look good for the most part.

It's not updated on the embedded version yet, so if that's what you're using then it's not available yet.  I made some other changes today, and want to make sure they haven't broken anything before I update that.

**Comment by opicron** [comment]
Great thanks for that! When I find the time I will create an docker build for ftelnet to easily deploy various setups. Will await the embedded version for now =).

**Comment by opicron** [comment]
Still not found the time to make an docker to self host fTelnet, but the embedded still does fine for now. I have made a test at:

https://thawk.nl/theforze-board/

When an new codepage is used in certain sections of the main menu (downloads, queue and new message). The whole font size changes somehow and results in an smaller window than initially drawn. Is this correct behaviour, and can we fix the font size (and skip redraw on code page changes).

I added the following configuration to the embed script. Following the source code I think that is correct?

Options.SkipRedrawWhenSameFontSize = true;

**Comment by opicron** [comment]
I partly fixed the rescaling of the font by hardcoding the resolution in css:

@media (min-width: 1200px) {
	.fTelnetClientContainer {
		width:1200px !important;
		height:720px !important;
	}
	.fTelnetCrtCanvas {
		width:1200px !important;
	}
}

**Comment by shadowlmd** [comment]
Offtopic: how can you switch codepages? There was an ANSI command for that very long time ago, but now it's not working.

**Comment by opicron** [comment]
We can close this request, it is working fully! Thanks again!
